---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name: 
        - htop
        - vim
        - git
        - fzf
        - bat
          #ln -s $(which fdfind) ~/.local/bin/fd          
        - fd-find

  - name: copy wallpaper file 
    copy:
      src: files/wallpaper.png 
      dest: /usr/share/backgrounds/ansible-wallpaper.png 
      owner: root
      group: root

  - name: set wallpaper 
    dconf:
      key: files/wallpaper.png 
      value: /usr/share/backgrounds/ansible-wallpaper.png 
      owner: root
      group: root
