---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name: 
        - htop
        - vim
        - git
        - fzf
        - bat
  - name: Install zsh
    apt: name=zsh
  - name: Change shell
    shell: chsh -s $(which zsh)
